### ISSUE TITLE
fatal error: mujoco.h: No such file or directory

### ISSUE THREAD

**Issue by ropo0107** [shadow-robot/mujoco_ros_pkgs#34]
when I catkin_make the mujoco_ros_pkgs, i meet some question.
`In file included from /home/sunshine/ros/shadow_demo/base/src/mujoco_ros_pkgs/mujoco_ros_control/src/visualization_utils.cpp:9:0:
/home/sunshine/ros/shadow_demo/base/src/mujoco_ros_pkgs/mujoco_ros_control/include/mujoco_ros_control/visualization_utils.h:12:20: **fatal error: mujoco.h: No such file or directory**
compilation terminated.
_mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/visualization_utils.dir/build.make:62:_ recipe for target 'mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/visualization_utils.dir/src/visualization_utils.cpp.o' failed
make[2]: *** [mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/visualization_utils.dir/src/visualization_utils.cpp.o] Error 1
CMakeFiles/Makefile2:13086: recipe for target 'mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/visualization_utils.dir/all' failed
make[1]: *** [mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/visualization_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target controller_manager_msgs_generate_messages_eus
[  2%] Building CXX object mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/robot_hw_sim.dir/src/robot_hw_sim.cpp.o
[  2%] Built target controller_manager_msgs_generate_messages_nodejs
In file included from /home/sunshine/ros/shadow_demo/base/src/mujoco_ros_pkgs/mujoco_ros_control/include/mujoco_ros_control/robot_hw_sim.h:16:0,
                 from /home/sunshine/ros/shadow_demo/base/src/mujoco_ros_pkgs/mujoco_ros_control/src/robot_hw_sim.cpp:9:
/home/sunshine/ros/shadow_demo/base/src/mujoco_ros_pkgs/mujoco_ros_control/include/mujoco_ros_control/robot_hw_sim_plugin.h:18:20: fatal error: mujoco.h: No such file or directory
compilation terminated.
mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/robot_hw_sim.dir/build.make:62: recipe for target 'mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/robot_hw_sim.dir/src/robot_hw_sim.cpp.o' failed
make[2]: *** [mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/robot_hw_sim.dir/src/robot_hw_sim.cpp.o] Error 1
CMakeFiles/Makefile2:13049: recipe for target 'mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/robot_hw_sim.dir/all' failed
make[1]: *** [mujoco_ros_pkgs/mujoco_ros_control/CMakeFiles/robot_hw_sim.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed`

I have add export `LD_LIBRARY_PATH=~/.mujoco/mujoco200/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} `and `export MUJOCO_KEY_PATH=~/.mujoco${MUJOCO_KEY_PATH} `to my ./bashrc file

**Comment by robotlearning123** [comment]
You need to change the path of mujoco. The packages use /home/user/mjpro150/xxx as default.
